FROM node:22-alpine AS ts_base_local


# Create app directory
WORKDIR /app
COPY package.json /app
COPY package-lock.json /app
COPY nx.json /app
COPY tsconfig.base.json /app
COPY eslint.base.config.mjs /app

RUN npm install -g nx nodemon
RUN npm install

ENV PORT=3080
EXPOSE 3080


FROM ts_base_local AS base

COPY apps/frontend/ ./apps/frontend

COPY packages/ts ./packages/ts


CMD ["nodemon", "--config", "apps/frontend/nodemon.json"]
